"""
Django settings for YPUnderground project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# LOGIN_URL，未登录时重定向到的 URL
# LOGIN_URL = 'https://yppf.yuanpei.life'
LOGIN_URL = 'http:localhost:8000/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%7!f&jx1obt5_z$5o9a@pvz-mn!g%6u%i9-t^7(4^*y-n@knbn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# '*'表示允许所有hosts访问
ALLOWED_HOSTS = ['*']

# Application definition
# 新创建的app需要在这里注册
# Appointment已在这里注册
#SECURE_SSL_REDIRECT = False
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #'sslserver',
    #'werkzeug_debugger_runserver',
    #'django_extensions',    # https访问
    'django.contrib.staticfiles',
    'django_apscheduler',  # django 计时任务
    # 'softdelete',  # django 逻辑删除
    'Appointment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'YPUnderground.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # templates 文件夹需要在这里注册
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 'loaders': (
            #     'django.template.loaders.filesystem.Loader',
            #     'django.template.loaders.app_directories.Loader',
            # ),
        },
    },
]

WSGI_APPLICATION = 'YPUnderground.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 使用自己的数据库的时候请修改这里的配置
    # 注意underground数据库需要事先创建
    # mysql -u root -p
    # create database underground charset='utf8';
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yuanpei_underground',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'liuzhanpeng',
        'PASSWORD': '', # modified by YHT
        # 'OPTIONS': {
        #     "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        # }
        'OPTIONS': {
             "init_command": "SET foreign_key_checks = 0;",
        #     "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

PasswordValidation = 'django.contrib.auth.password_validation.'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': PasswordValidation + 'UserAttributeSimilarityValidator',
    },
    {
        'NAME': PasswordValidation + 'MinimumLengthValidator',
    },
    {
        'NAME': PasswordValidation + 'CommonPasswordValidator',
    },
    {
        'NAME': PasswordValidation + 'NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
# 语言和时间的调整。如果有显示格式问题很可能是这边限制了
LANGUAGES = [
    ('zh-Hans', _('Chinese')),
]

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = False

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = (
#    os.path.join(BASE_DIR, 'static'), 
#    )

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')


# password
# https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#auth-password-storage
PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)