# Generated by Django 3.2.4 on 2021-08-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College_Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='是否显示')),
                ('announcement', models.CharField(max_length=256, null=True, verbose_name='通知内容')),
            ],
            options={
                'verbose_name': '全院公告',
                'verbose_name_plural': '全院公告',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Rid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='房间编号')),
                ('Rtitle', models.CharField(max_length=32, verbose_name='房间名称')),
                ('Rmin', models.IntegerField(default=0, verbose_name='房间预约人数下限')),
                ('Rmax', models.IntegerField(default=20, verbose_name='房间使用人数上限')),
                ('Rstart', models.TimeField(verbose_name='最早预约时间')),
                ('Rfinish', models.TimeField(verbose_name='最迟预约时间')),
                ('Rlatest_time', models.DateTimeField(auto_now_add=True, verbose_name='摄像头心跳')),
                ('Rpresent', models.IntegerField(default=0, verbose_name='目前人数')),
                ('Rstatus', models.SmallIntegerField(choices=[(0, 'Permitted'), (1, 'Suspended')], default=0, verbose_name='房间状态')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['Rid'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('Sname', models.CharField(max_length=64, verbose_name='姓名')),
                ('Scredit', models.IntegerField(default=3, verbose_name='信用分')),
                ('superuser', models.IntegerField(default=0, verbose_name='超级用户')),
                ('pinyin', models.CharField(max_length=20, null=True, verbose_name='拼音')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['Sid'],
            },
        ),
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False, verbose_name='预约编号')),
                ('Atime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('Astart', models.DateTimeField(verbose_name='开始时间')),
                ('Afinish', models.DateTimeField(verbose_name='结束时间')),
                ('Ausage', models.CharField(max_length=256, null=True, verbose_name='用途')),
                ('Aannouncement', models.CharField(blank=True, max_length=256, null=True, verbose_name='预约通知')),
                ('Anon_yp_num', models.IntegerField(default=0, verbose_name='外院人数')),
                ('Ayp_num', models.IntegerField(default=0, verbose_name='院内人数')),
                ('Astatus', models.IntegerField(choices=[(0, 'Canceled'), (1, 'Appointed'), (2, 'Processing'), (3, 'Waiting'), (4, 'Confirmed'), (5, 'Violated'), (6, 'Judged')], default=1, verbose_name='预约状态')),
                ('Acamera_check_num', models.IntegerField(default=0, verbose_name='检查次数')),
                ('Acamera_ok_num', models.IntegerField(default=0, verbose_name='人数合格次数')),
                ('Areason', models.IntegerField(choices=[(0, 'R Noviolated'), (1, 'R Late'), (2, 'R Toolittle'), (3, 'R Else')], default=0, verbose_name='违约原因')),
                ('Room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appoint_list', to='Appointment.room', verbose_name='房间号')),
                ('major_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appointment.student', verbose_name='Appointer')),
                ('students', models.ManyToManyField(db_index=True, related_name='appoint_list', to='Appointment.Student')),
            ],
            options={
                'verbose_name': '预约信息',
                'verbose_name_plural': '预约信息',
                'ordering': ['Aid'],
            },
        ),
    ]
