# Generated by Django 3.2.4 on 2021-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Secret',
            field=models.CharField(default=0, max_length=50, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
