# Generated by Django 3.0.3 on 2020-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'College_Announcement',
            fields = [
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='是否显示')),
                ('announcement', models.CharField(max_length=256, null=True, verbose_name='通知内容')),
            ],
        ),
    ]
