# Generated by Django 3.2.4 on 2021-08-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_student_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Tid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='老师号')),
                ('Secret', models.CharField(max_length=50, verbose_name='密码')),
                ('Sname', models.CharField(max_length=64, verbose_name='姓名')),
                ('Scredit', models.IntegerField(default=3, verbose_name='信用分')),
                ('superuser', models.IntegerField(default=0, verbose_name='超级用户')),
                ('pinyin', models.CharField(max_length=20, null=True, verbose_name='拼音')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'ordering': ['Tid'],
            },
        ),
        migrations.CreateModel(
            name='SidAndWid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wxid', models.CharField(max_length=50, verbose_name='wxid')),
                ('status', models.IntegerField(default=0, verbose_name='审核')),
                ('Rid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.room', verbose_name='房间号id外键')),
                ('Sid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.student', verbose_name='学生id外键')),
            ],
            options={
                'verbose_name': '学生微信通知表',
                'verbose_name_plural': '学生微信通知表',
                'ordering': ['Sid_id'],
            },
        ),
    ]
